### PR TITLE
Add Support for VKB Kosmosima SCG Right

### PR DESCRIPTION
**Pull request by ajhewett**
This pull request adds:
- support for the VKB Kosmosima SCG Right
- my current ED bindings for VKB Kosmosima SCG Right together with a Thrustmaster T1600 Throttle
- a Dockerfile with the necessary apache2 config 

I have been running EDRefCard in a Docker container on my home NAS while tinkering with the bindings.  Works great!

The reference sheet image was taken from https://vkbcontrollers.com/wp-content/uploads/2019/01/SCG_Right.pdf

NOTE: I don't have afdesign so created a .svg file with Inkscape.

### CODE REVIEW

**Comment by ajhewett** [comment]
@richardbuckle  Any feedback?
I'm happy to change or remove anything. For example, the Dockerfile and apache2 config was mostly for my convenience.

**Comment by richardbuckle** [comment]
Thanks for the reminder. With all the real life stuff going on, I've been a bit distracted from the hobby projects. Looks good at first glance and I shall make time to check the details. 

I'm not very au fait with Docker but the format looks reasonable enough, so provided it meshes with my own Apache config I'm not opposed to it. The purist view would be to separate the tasks into two PRs but I'd say that's overkill here.

**Comment by richardbuckle** [comment]
Oh and BTW SVG files are fine. Any portable vector format is fine. I'm not wedded to afdesign, it just happens to be what jgm used back in the day.

Some other questions:

1. Would you be willing to extend README.md with instructions for applying your Dockerfile (even if it feels obvious to you)?
2. I see that the grip has a left-handed variant. Without blocking this particular PR, is it something you could easily do another PR for using VKB's PDF for that?

**Comment by richardbuckle** [comment]
Where are my manners? THANK YOU for taking the trouble to do this: I know first hand what painstaking work it is.

**Comment by ajhewett** [comment]
@richardbuckle thanks for the feedback.
1. I will update the PR with some docker instructions in the README.md
2. I can do the left-handed grip sometime. I want to purchase one when they come back in stock so that would be a good time for a new PR.

**Comment by ajhewett** [comment]
@richardbuckle I have added some Docker instructions, support for the left-hand grip and a working bindings file for my dual VKB setup.

CMDR ajh0

**Pull request merged**
